name: smart_locker_app
description: Smart Locker App

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^2.30.0
  firebase_database: ^10.5.0
  http: ^1.2.0
  audioplayers: ^5.2.1

flutter:
  uses-material-design: true

